### ISSUE TITLE
Image is unstable/flashing and has alternating garbage when used on C128

### ISSUE THREAD

**Issue by nick3092** [T-Pau/Anykey#3]
When using Anykey on my C128, the keyboard image looks like it's flashing. And it also looks like some garbage characters are faintly being shown. I confirmed the issue on both my 1902 and 1702, so it doesn't seem to be a monitor issue. 

The same thing occurs when using my C128 in C64 mode. The title/splash screen is normal. But once the keyboard image loads, it is unstable. Using it on my C64 bread bin, the keyboard image is stable/fine. 

When I took a picture with my phone, you can see in the dark area where the garbage is shown, and in the light areas where it shows normally. I know that the camera is interpreting the crt scan, and I'm guessing that is the dark area in the picture.

If it makes a difference, the VDC ram on my C128 has been upgraded to 64k. It was a direct chip swap on the board, not one of the daughter boards. But as I understand it, that shouldn't change anything. 

![EC9DE803-5207-4D75-8706-00A1C5B85789](https://user-images.githubusercontent.com/66426173/159975780-8b89f1ce-fd93-4599-92ee-3aeea75b722a.jpeg)

**Comment by dillof** [comment]
Is your C128 PAL or NTSC? Anykey currently doesn't support NTSC systems.

**Comment by nick3092** [comment]
NTSC, that would probably explain it. But my C64 should also be NTSC, and doesn't exhibit the same issue.

**Comment by dillof** [comment]
Since NTSC has less scanlines than PAL, there are less CPU cycles per frame on NTSC. The C128 has more keys to check than the C64, and that takes too long for NTSC. I'll see if I can speed it up so it fits.

**Comment by dillof** [comment]
This is now fixed. I opted for updating only half the keyboard each frame.
