### ISSUE TITLE
C128 extended keys do not work anymore

### ISSUE THREAD

**Issue by pdaehne** [T-Pau/Anykey#4]
Since version 1.6, most of the extended keys of the C128 keyboard do not work anymore. They're working in 1.5. See screenshot with affected keys.
![c128_extended_keys](https://user-images.githubusercontent.com/22456078/182704012-53a5a68e-c86d-4617-804a-a2cbc826b17e.jpeg)

**Comment by dillof** [comment]
I can reproduce the problem, I'll look into it.

**Comment by dillof** [comment]
This is now fixed. I'll release a new version containing the fix shortly.
